<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>HomeScreenCompanion.Spike</AssemblyName>
    <RootNamespace>HomeScreenCompanion.Spike</RootNamespace>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.10.0.24-beta2" />
  </ItemGroup>

</Project>