<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<AssemblyTitle>Home Screen Companion</AssemblyTitle>
		<AssemblyName>HomeScreenCompanion</AssemblyName>
		<RootNamespace>HomeScreenCompanion</RootNamespace>

		<Product>Home Screen Companion</Product>

		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

	</PropertyGroup>

	<Target Name="ReadVersionFromFile" BeforeTargets="GetAssemblyVersion">
		<ReadLinesFromFile File="$(MSBuildThisFileDirectory)../version.txt">
			<Output TaskParameter="Lines" ItemName="VersionLines" />
		</ReadLinesFromFile>
		<PropertyGroup>
			<Version>@(VersionLines, '')</Version>
			<AssemblyVersion>@(VersionLines, '')</AssemblyVersion>
			<FileVersion>@(VersionLines, '')</FileVersion>
		</PropertyGroup>
	</Target>

	<Target Name="AppendCommitShaToInformationalVersion" BeforeTargets="AddSourceRevisionToInformationalVersion" Condition="'$(SourceRevisionId)' != ''">
		<PropertyGroup>
			<InformationalVersion>$(Version)-$(SourceRevisionId.Substring(0, 7))</InformationalVersion>
		</PropertyGroup>
	</Target>

	<ItemGroup>
	  <None Remove="thumb.png" />
	  <None Remove="LemonMilk.otf" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="thumb.png" />
	  <EmbeddedResource Include="LemonMilk.otf" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="SkiaSharp" Version="2.88.9" />
	  <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	  <PackageReference Include="System.Memory" Version="4.6.0" />
	  <PackageReference Include="MediaBrowser.Common" Version="4.10.0.24-beta2" />
	  <PackageReference Include="MediaBrowser.Server.Core" Version="4.10.0.24-beta2" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="HomeScreenCompanion.Tests" />
	</ItemGroup>

</Project>