/// <reference types="vitest" />
//
// Tests for `modules/filters/miFilters.ts`, two layers:
//
//  1. Fresh structural tests for `propertyOptionsHtml` / `getMiHintHtml`
//     (below) — happy-dom-free HTML-substring checks. Each verifies *one*
//     observable property of the generated HTML so a whitespace tweak
//     upstream won't cascade into a brittle full-string diff.
//
//  2. A data-driven *mirror* of the legacy snapshot suite
//     (`src/__tests__/legacy/mi-filters.test.ts`, generated by
//     `npm run test:legacy`) for `getMiValueHtml`,
//     `getMediaInfoRuleHtml`, `getMediaInfoFilterGroupHtml`, and
//     `readMiFiltersFromContainer`. Expected outputs are read straight
//     from the legacy `.snap` file — the TS module must reproduce them
//     byte-for-byte with empty deps (the legacy fixture runs with
//     unpopulated caches). The populated-deps branches, which the
//     fixture cannot reach, are covered structurally at the bottom.

import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

import {
    propertyOptionsHtml,
    getMiHintHtml,
    getMiValueHtml,
    getMediaInfoRuleHtml,
    getMediaInfoFilterGroupHtml,
    readMiFiltersFromContainer,
    type MiFilterDeps,
} from './miFilters';
import type { MediaInfoFilterGroup } from './savedFilters';

const EMPTY_DEPS = { users: null, collections: [], playlists: [], tags: [] };

describe('propertyOptionsHtml', () => {
    it('renders every group label in the legacy order', () => {
        const html = propertyOptionsHtml('');
        // Spot-check every group label. Order matters: Video first,
        // Activity last (legacy.js:1015-1022).
        expect(html.indexOf('<optgroup label="Video"')).toBeGreaterThanOrEqual(0);
        expect(html.indexOf('<optgroup label="Audio"')).toBeGreaterThan(html.indexOf('<optgroup label="Video"'));
        expect(html.indexOf('<optgroup label="Content"')).toBeGreaterThan(html.indexOf('<optgroup label="Audio"'));
        expect(html.indexOf('<optgroup label="Music"')).toBeGreaterThan(html.indexOf('<optgroup label="Content"'));
        expect(html.indexOf('<optgroup label="Metrics"')).toBeGreaterThan(html.indexOf('<optgroup label="Music"'));
        expect(html.indexOf('<optgroup label="Activity"')).toBeGreaterThan(html.indexOf('<optgroup label="Metrics"'));
    });

    it('emits one <option> per prop tuple with value + label', () => {
        const html = propertyOptionsHtml('');
        // value attr is the prop name; the text inside the option is
        // the human-readable label. e.g. value="Collection" with
        // text "In Collection" (legacy.js:1018).
        expect(html).toContain('<option value="Resolution"');
        expect(html).toContain('>Resolution</option>');
        expect(html).toContain('<option value="HDR"');
        expect(html).toContain('<option value="Tag"');
        expect(html).toContain('<option value="Collection"');
        expect(html).toContain('>In Collection</option>');
        expect(html).toContain('<option value="BitRate"');
        expect(html).toContain('>Bit Rate (kbps)</option>');
    });

    it('marks no option selected when selected is empty', () => {
        const html = propertyOptionsHtml('');
        // No "selected" attribute anywhere — the function never emits
        // it unless `selected` matches a prop value.
        expect(html).not.toContain(' selected');
    });

    it('marks the matching option as selected', () => {
        const html = propertyOptionsHtml('Resolution');
        expect(html).toContain('<option value="Resolution" selected');
        // Pick a different prop in another group; verify it stays
        // un-selected so the selection doesn't bleed across options.
        expect(html).toContain('<option value="HDR"');
        expect(html).not.toContain('<option value="HDR" selected');
    });

    it('selects an option in a non-first group', () => {
        const html = propertyOptionsHtml('Artist');
        // Artist lives under Music — the selection should not show up
        // in Video / Audio / Content / Metrics / Activity headers.
        const musicIdx = html.indexOf('<optgroup label="Music"');
        const afterMusic = html.slice(musicIdx);
        expect(afterMusic).toContain('<option value="Artist" selected');
    });

    it('emits the legacy Resolution subgroup (4K / 8K / etc.) untouched', () => {
        const html = propertyOptionsHtml('');
        // Resolution values match the labels exactly in the legacy
        // tuple, but the option *value* is the prop name and the
        // option *text* is the human label.
        expect(html).toContain('<option value="Resolution"');
        expect(html).toContain('<option value="VideoCodec"');
        expect(html).toContain('<option value="HDR"');
        // Confirm the Video group ends before the Audio group begins
        // (i.e. no <optgroup> nested inside another).
        const videoEnd = html.indexOf('</optgroup>');
        const audioStart = html.indexOf('<optgroup label="Audio"');
        expect(videoEnd).toBeLessThan(audioStart);
    });
});

describe('getMiHintHtml', () => {
    it('renders the empty hint div for a prop that has no text-match semantics', () => {
        // Resolution is not in MI_TEXT_MATCH_PROPS and is not ImdbId/TvdbId.
        const html = getMiHintHtml('Resolution');
        expect(html).toBe('<div class="mi-rule-hint"></div>');
    });

    it('renders the populated hint for a prop in MI_TEXT_MATCH_PROPS', () => {
        const html = getMiHintHtml('Title');
        expect(html).toContain('<div class="mi-rule-hint"');
        expect(html).toContain('One value per line');
        expect(html).toContain('&mdash;');
        expect(html).toContain('<em>');
        expect(html).toContain('any</em> line matches');
    });

    it('renders the populated hint for ImdbId even though it is not in MI_TEXT_MATCH_PROPS', () => {
        // The legacy condition has two carve-outs: MI_TEXT_MATCH_PROPS
        // OR exactly ImdbId/TvdbId. Verify both carve-outs.
        const html = getMiHintHtml('ImdbId');
        expect(html).toContain('One value per line');
    });

    it('renders the populated hint for TvdbId via the same carve-out branch', () => {
        const html = getMiHintHtml('TvdbId');
        expect(html).toContain('One value per line');
    });

    it('renders the populated hint for every MI_TEXT_MATCH_PROPS member', () => {
        // Belt-and-braces: spot-check one entry from each "shape" of
        // list membership to make sure the legacy indexOf check still
        // picks them all up after the constant was lifted.
        const members = [
            'Tag', 'Title', 'EpisodeTitle', 'Overview', 'Studio',
            'Genre', 'Actor', 'Director', 'Writer', 'ContentRating',
            'AudioLanguage', 'Artist', 'Album', 'FolderPath', 'Country',
        ];
        for (const m of members) {
            expect(getMiHintHtml(m)).toContain('One value per line');
        }
    });
});

// ─── Populated-deps branches (the legacy fixture caches are empty) ────────────

describe('getMiValueHtml with populated deps', () => {
    const deps: MiFilterDeps = {
        users: [{ Id: 'u1', Name: 'Alice' }, { Id: 'u2', Name: 'Bob' }],
        collections: [{ Name: 'Star Wars' }, { Name: 'He said "hi"' }],
        playlists: [{ Name: 'My Mix' }],
        tags: ['4K', 'HDR'],
    };

    it('renders resolved users in the user select with the saved user selected', () => {
        const html = getMiValueHtml('IsPlayed', '', 'Watched', 'u2', deps);
        expect(html).toContain('<option value="u1">Alice</option>');
        expect(html).toContain('<option value="u2" selected>Bob</option>');
        // The __current__ special is IsPlayed-only and stays unselected.
        expect(html).toContain('<option value="__current__">Current user (viewer)</option>');
        expect(html).toContain('<option value="__any__">Any user</option>');
    });

    it('renders collections and escapes double quotes in option values', () => {
        const html = getMiValueHtml('Collection', '', 'Star Wars', '', deps);
        expect(html).toContain('<option value="Star Wars" selected>Star Wars</option>');
        expect(html).toContain('<option value="He said &quot;hi&quot;">He said "hi"</option>');
        expect(html).toContain('<option value="">-- Select --</option>');
    });

    it('renders the tag dropdown branch when tags are cached', () => {
        const html = getMiValueHtml('Tag', 'contains', 'HDR', '', deps);
        expect(html).toContain('-- Select tag --');
        expect(html).toContain('<option value="HDR" selected>HDR</option>');
        expect(html).toContain('<option value="4K">4K</option>');
        // The dropdown branch replaces the free-text textarea entirely.
        expect(html).not.toContain('txtMiValue');
    });

    it('renders playlists from the playlist list, not the collection list', () => {
        const html = getMiValueHtml('Playlist', '', 'My Mix', '', deps);
        expect(html).toContain('<option value="My Mix" selected>My Mix</option>');
        expect(html).not.toContain('Star Wars');
    });
});

// ─── Build → read round-trip ───────────────────────────────────────────────────

describe('build → read round-trip', () => {
    it('readMiFiltersFromContainer inverts getMediaInfoFilterGroupHtml', () => {
        const html = getMediaInfoFilterGroupHtml(
            { Operator: 'AND', GroupOperator: 'AND', Criteria: ['MediaType:Movie', '4K'] },
            0,
            true,
            EMPTY_DEPS,
        );
        const container = document.createElement('div');
        container.innerHTML = html;
        expect(readMiFiltersFromContainer(container)).toEqual([
            { Operator: 'AND', GroupOperator: 'AND', Criteria: ['MediaType:Movie', '4K'] },
        ]);
    });

    it('round-trips a negated rule and the Episode checkbox', () => {
        const html = getMediaInfoFilterGroupHtml(
            { Operator: 'OR', GroupOperator: 'AND', Criteria: ['!MediaType:EpisodeIncludeSeries', 'Year:<=:1999'] },
            1,
            false,
            EMPTY_DEPS,
        );
        const container = document.createElement('div');
        container.innerHTML = html;
        expect(readMiFiltersFromContainer(container)).toEqual([
            {
                Operator: 'OR',
                GroupOperator: 'AND',
                Criteria: ['!MediaType:EpisodeIncludeSeries', 'Year:<=:1999'],
            },
        ]);
    });
});
