/// <reference types="vitest" />
//
// Tests for `modules/filters/miFilters.ts`, two layers:
//
//  1. Fresh structural tests for `propertyOptionsHtml` / `getMiHintHtml`
//     (below) — happy-dom-free HTML-substring checks. Each verifies *one*
//     observable property of the generated HTML so a whitespace tweak
//     upstream won't cascade into a brittle full-string diff.
//
//  2. A data-driven *mirror* of the legacy snapshot suite
//     (`src/__tests__/legacy/mi-filters.test.ts`, generated by
//     `npm run test:legacy`) for `getMiValueHtml`,
//     `getMediaInfoRuleHtml`, `getMediaInfoFilterGroupHtml`, and
//     `readMiFiltersFromContainer`. Expected outputs are read straight
//     from the legacy `.snap` file — the TS module must reproduce them
//     byte-for-byte with empty deps (the legacy fixture runs with
//     unpopulated caches). The populated-deps branches, which the
//     fixture cannot reach, are covered structurally at the bottom.

import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

import {
    propertyOptionsHtml,
    getMiHintHtml,
    getMiValueHtml,
    getMediaInfoRuleHtml,
    getMediaInfoFilterGroupHtml,
    readMiFiltersFromContainer,
    type MiFilterDeps,
} from './miFilters';
import type { MediaInfoFilterGroup } from './savedFilters';

describe('propertyOptionsHtml', () => {
    it('renders every group label in the legacy order', () => {
        const html = propertyOptionsHtml('');
        // Spot-check every group label. Order matters: Video first,
        // Activity last (legacy.js:1015-1022).
        expect(html.indexOf('<optgroup label="Video"')).toBeGreaterThanOrEqual(0);
        expect(html.indexOf('<optgroup label="Audio"')).toBeGreaterThan(html.indexOf('<optgroup label="Video"'));
        expect(html.indexOf('<optgroup label="Content"')).toBeGreaterThan(html.indexOf('<optgroup label="Audio"'));
        expect(html.indexOf('<optgroup label="Music"')).toBeGreaterThan(html.indexOf('<optgroup label="Content"'));
        expect(html.indexOf('<optgroup label="Metrics"')).toBeGreaterThan(html.indexOf('<optgroup label="Music"'));
        expect(html.indexOf('<optgroup label="Activity"')).toBeGreaterThan(html.indexOf('<optgroup label="Metrics"'));
    });

    it('emits one <option> per prop tuple with value + label', () => {
        const html = propertyOptionsHtml('');
        // value attr is the prop name; the text inside the option is
        // the human-readable label. e.g. value="Collection" with
        // text "In Collection" (legacy.js:1018).
        expect(html).toContain('<option value="Resolution"');
        expect(html).toContain('>Resolution</option>');
        expect(html).toContain('<option value="HDR"');
        expect(html).toContain('<option value="Tag"');
        expect(html).toContain('<option value="Collection"');
        expect(html).toContain('>In Collection</option>');
        expect(html).toContain('<option value="BitRate"');
        expect(html).toContain('>Bit Rate (kbps)</option>');
    });

    it('marks no option selected when selected is empty', () => {
        const html = propertyOptionsHtml('');
        // No "selected" attribute anywhere — the function never emits
        // it unless `selected` matches a prop value.
        expect(html).not.toContain(' selected');
    });

    it('marks the matching option as selected', () => {
        const html = propertyOptionsHtml('Resolution');
        expect(html).toContain('<option value="Resolution" selected');
        // Pick a different prop in another group; verify it stays
        // un-selected so the selection doesn't bleed across options.
        expect(html).toContain('<option value="HDR"');
        expect(html).not.toContain('<option value="HDR" selected');
    });

    it('selects an option in a non-first group', () => {
        const html = propertyOptionsHtml('Artist');
        // Artist lives under Music — the selection should not show up
        // in Video / Audio / Content / Metrics / Activity headers.
        const musicIdx = html.indexOf('<optgroup label="Music"');
        const afterMusic = html.slice(musicIdx);
        expect(afterMusic).toContain('<option value="Artist" selected');
    });

    it('emits the legacy Resolution subgroup (4K / 8K / etc.) untouched', () => {
        const html = propertyOptionsHtml('');
        // Resolution values match the labels exactly in the legacy
        // tuple, but the option *value* is the prop name and the
        // option *text* is the human label.
        expect(html).toContain('<option value="Resolution"');
        expect(html).toContain('<option value="VideoCodec"');
        expect(html).toContain('<option value="HDR"');
        // Confirm the Video group ends before the Audio group begins
        // (i.e. no <optgroup> nested inside another).
        const videoEnd = html.indexOf('</optgroup>');
        const audioStart = html.indexOf('<optgroup label="Audio"');
        expect(videoEnd).toBeLessThan(audioStart);
    });
});

describe('getMiHintHtml', () => {
    it('renders the empty hint div for a prop that has no text-match semantics', () => {
        // Resolution is not in MI_TEXT_MATCH_PROPS and is not ImdbId/TvdbId.
        const html = getMiHintHtml('Resolution');
        expect(html).toBe('<div class="mi-rule-hint"></div>');
    });

    it('renders the populated hint for a prop in MI_TEXT_MATCH_PROPS', () => {
        const html = getMiHintHtml('Title');
        expect(html).toContain('<div class="mi-rule-hint"');
        expect(html).toContain('One value per line');
        expect(html).toContain('&mdash;');
        expect(html).toContain('<em>');
        expect(html).toContain('any</em> line matches');
    });

    it('renders the populated hint for ImdbId even though it is not in MI_TEXT_MATCH_PROPS', () => {
        // The legacy condition has two carve-outs: MI_TEXT_MATCH_PROPS
        // OR exactly ImdbId/TvdbId. Verify both carve-outs.
        const html = getMiHintHtml('ImdbId');
        expect(html).toContain('One value per line');
    });

    it('renders the populated hint for TvdbId via the same carve-out branch', () => {
        const html = getMiHintHtml('TvdbId');
        expect(html).toContain('One value per line');
    });

    it('renders the populated hint for every MI_TEXT_MATCH_PROPS member', () => {
        // Belt-and-braces: spot-check one entry from each "shape" of
        // list membership to make sure the legacy indexOf check still
        // picks them all up after the constant was lifted.
        const members = [
            'Tag', 'Title', 'EpisodeTitle', 'Overview', 'Studio',
            'Genre', 'Actor', 'Director', 'Writer', 'ContentRating',
            'AudioLanguage', 'Artist', 'Album', 'FolderPath', 'Country',
        ];
        for (const m of members) {
            expect(getMiHintHtml(m)).toContain('One value per line');
        }
    });
});

// ─── Mirror of the legacy mi-filters snapshot suite ───────────────────────────
//
// Same technique as `criteria.test.ts`: load the legacy Vitest `.snap`
// file, re-evaluate it in a sandbox, and compare each TS output against
// the captured legacy value. The legacy fixture runs with unpopulated
// caches (`_miUsers` null, empty collection/playlist/tag lists), so the
// mirror feeds `EMPTY_DEPS` — and the populated branches get structural
// coverage in the last describe below.

const SNAP_PATH = path.resolve(
    __dirname,
    '..',
    '..',
    '__tests__',
    'legacy',
    '__snapshots__',
    'mi-filters.test.ts.snap',
);

const legacySnap: Record<string, unknown> = (() => {
    if (!fs.existsSync(SNAP_PATH)) {
        throw new Error(
            `Legacy mi-filters snapshot not found at ${SNAP_PATH}. ` +
            `Run \`npm run test:legacy\` (or \`npm run build:legacy\`) once to generate it.`,
        );
    }
    const src = fs.readFileSync(SNAP_PATH, 'utf8');
    const exportsObj: Record<string, unknown> = {};
    const moduleObj = { exports: exportsObj };
    // eslint-disable-next-line no-new-func
    new Function('exports', 'module', src)(exportsObj, moduleObj);
    return moduleObj.exports as Record<string, unknown>;
})();

/** Look up the `index`-th (1-based) snapshot value stored under `testPath`. */
function snapValue(testPath: string, index: number): unknown {
    const v = legacySnap[`${testPath} ${index + 1}`];
    if (v === undefined) {
        throw new Error(
            `Missing legacy snapshot: "${testPath} #${index + 1}". ` +
            `Available keys: ${Object.keys(legacySnap).join(', ')}`,
        );
    }
    return v;
}

/**
 * Undo the Vitest snapshot serialization (see `criteria.test.ts` for the
 * same ladder, plus one HTML-specific rung):
 *   - Non-strings, `''`, `'undefined'` pass through.
 *   - Strict `JSON.parse` recovers plain strings, `null`, numbers.
 *   - Pre-escaped (`\r`/`\n`/`\t`) `JSON.parse` recovers multi-line
 *     strings without inner quotes.
 *   - Vitest prints strings as `"` + raw content + `"` with inner double
 *     quotes UN-escaped — every HTML snapshot lands here. Strip the outer
 *     pair and return the inner content verbatim.
 *   - Object/array literals (quoted keys, trailing commas) evaluate as JS.
 */
function normalize(value: unknown): unknown {
    if (typeof value !== 'string') return value;
    const trimmed = value.trim();
    if (trimmed === '') return '';
    if (trimmed === 'undefined') return undefined;

    const tryParse = (s: string): unknown => {
        try {
            return JSON.parse(s);
        } catch {
            return undefined;
        }
    };

    const fromStrict = tryParse(trimmed);
    if (fromStrict !== undefined) return fromStrict;

    const escaped = trimmed
        .replace(/\r/g, '\\r')
        .replace(/\n/g, '\\n')
        .replace(/\t/g, '\\t');
    const fromEscaped = tryParse(escaped);
    if (fromEscaped !== undefined) return fromEscaped;

    if (
        trimmed.length >= 2 &&
        trimmed.charAt(0) === '"' &&
        trimmed.charAt(trimmed.length - 1) === '"'
    ) {
        return trimmed.slice(1, -1);
    }

    try {
        // eslint-disable-next-line no-new-func
        return new Function(`return (${trimmed});`)() as unknown;
    } catch {
        return value;
    }
}

const EMPTY_DEPS: MiFilterDeps = { users: null, collections: [], playlists: [], tags: [] };

// ---------- data-driven mirror cases ----------

type MiOp = 'miValue' | 'miRule' | 'miGroup' | 'readMi';

interface MiCase {
    /** Full legacy test path (`<describe ><describe ><it>`). */
    readonly title: string;
    readonly op: MiOp;
    /** Inputs to feed through the TS function, in order. */
    readonly inputs: ReadonlyArray<unknown>;
}

interface DomRule {
    prop: string;
    kind: 'select' | 'number' | 'text' | 'mediaType';
    val?: string;
    op?: string;
    userId?: string;
    textOp?: string;
    includeParent?: boolean;
    not?: boolean;
}

interface DomGroup {
    op: string;
    groupOp: string;
    rules: DomRule[];
}

function ruleHtml(r: DomRule): string {
    const notBtn = '<button type="button" class="btnNotToggle" data-not="' + (r.not ? '1' : '0') + '"></button>';
    const propSel = '<select class="selMiProperty"><option value="' + r.prop + '">' + r.prop + '</option></select>';
    let valueControls = '';
    if (r.kind === 'select') {
        valueControls = '<select class="selMiValue"><option value="' + (r.val ?? '') + '">' + (r.val ?? '') + '</option></select>';
    } else if (r.kind === 'number') {
        valueControls =
            '<select class="selMiOp"><option value="' + (r.op ?? '') + '">' + (r.op ?? '') + '</option></select>' +
            '<input class="txtMiNum" type="number" value="' + (r.val ?? '') + '" />';
    } else if (r.kind === 'text') {
        valueControls = '<textarea class="txtMiValue">' + (r.val ?? '') + '</textarea>';
    } else {
        valueControls =
            '<select class="selMiValue"><option value="' + (r.val ?? '') + '">' + (r.val ?? '') + '</option></select>' +
            '<input type="checkbox" class="chkIncludeParentSeries"' + (r.includeParent ? ' checked' : '') + ' />';
    }
    const userSel = r.userId ? '<select class="selMiUser"><option value="' + r.userId + '">' + r.userId + '</option></select>' : '';
    const textOpSel = r.textOp ? '<select class="selMiTextOp"><option value="' + r.textOp + '">' + r.textOp + '</option></select>' : '';
    return '<div class="mi-rule">' + notBtn + propSel + textOpSel + userSel + valueControls + '</div>';
}

function makeContainer(groups: DomGroup[]): HTMLElement {
    const container = document.createElement('div');
    container.innerHTML = groups.map(function (g) {
        return '<div class="mediainfo-filter-group" data-op="' + g.op + '" data-group-op="' + g.groupOp + '">' +
            g.rules.map(ruleHtml).join('') +
            '</div>';
    }).join('');
    return container;
}

const PREFIX = 'media-info filter builders > ';

const CASES: ReadonlyArray<MiCase> = [
    // ---- getMiValueHtml ----
    { title: 'getMiValueHtml > Resolution dropdown presets (4K selected)', op: 'miValue', inputs: ['Resolution', '', '4K', ''] },
    { title: 'getMiValueHtml > Resolution dropdown with no saved value', op: 'miValue', inputs: ['Resolution', '', '', ''] },
    { title: 'getMiValueHtml > MediaType Episode (include-parent checkbox visible, unchecked)', op: 'miValue', inputs: ['MediaType', '', 'Episode', ''] },
    { title: 'getMiValueHtml > MediaType EpisodeIncludeSeries (Episode selected, checkbox checked)', op: 'miValue', inputs: ['MediaType', '', 'EpisodeIncludeSeries', ''] },
    { title: 'getMiValueHtml > MediaType Movie', op: 'miValue', inputs: ['MediaType', '', 'Movie', ''] },
    { title: 'getMiValueHtml > IsPlayed user select with __current__ selected (fixture: no users)', op: 'miValue', inputs: ['IsPlayed', '', 'Watched', '__current__'] },
    { title: 'getMiValueHtml > IsPlayed user select with __any__ selected (fixture: no users)', op: 'miValue', inputs: ['IsPlayed', '', 'Unwatched', '__any__'] },
    { title: 'getMiValueHtml > Collection select (fixture: no collections cached)', op: 'miValue', inputs: ['Collection', '', 'Star Wars', ''] },
    { title: 'getMiValueHtml > Playlist select (fixture: no playlists cached)', op: 'miValue', inputs: ['Playlist', '', 'My Mix', ''] },
    { title: 'getMiValueHtml > Tag free-text textarea (fixture: no tags cached), contains op', op: 'miValue', inputs: ['Tag', 'contains', '4K', ''] },
    { title: 'getMiValueHtml > Tag free-text textarea with exact op and comma-separated legacy value', op: 'miValue', inputs: ['Tag', 'exact', 'a,b,c', ''] },
    { title: 'getMiValueHtml > Year numeric (op <=, value 1999, no unit label)', op: 'miValue', inputs: ['Year', '<=', '1999', ''] },
    { title: 'getMiValueHtml > PlayCount numeric (default op >= when savedOp empty; unit plays)', op: 'miValue', inputs: ['PlayCount', '', '3', ''] },
    { title: 'getMiValueHtml > FileSize numeric (unit MB)', op: 'miValue', inputs: ['FileSize', '>', '2048', ''] },
    { title: 'getMiValueHtml > Title text match (contains default, placeholder)', op: 'miValue', inputs: ['Title', '', 'Batman', ''] },
    { title: 'getMiValueHtml > Actor text match (exact default, placeholder)', op: 'miValue', inputs: ['Actor', '', 'Tom Hanks', ''] },
    { title: 'getMiValueHtml > InProgress dropdown (single option, no user select)', op: 'miValue', inputs: ['InProgress', '', 'InProgress', ''] },
    { title: 'getMiValueHtml > LastPlayed numeric with __any__ user (user select prepended)', op: 'miValue', inputs: ['LastPlayed', '<=', '7', '__any__'] },
    { title: 'getMiValueHtml > unknown prop falls back to the plain textarea', op: 'miValue', inputs: ['CustomProp', '', 'hello', ''] },
    { title: 'getMiValueHtml > ImdbId falls back to the plain textarea (not a text-match prop)', op: 'miValue', inputs: ['ImdbId', '', 'tt1234567', ''] },
    // ---- getMediaInfoRuleHtml ----
    { title: 'getMediaInfoRuleHtml > simple Resolution:4K rule', op: 'miRule', inputs: ['Resolution:4K'] },
    { title: 'getMediaInfoRuleHtml > shorthand 4K rule', op: 'miRule', inputs: ['4K'] },
    { title: 'getMediaInfoRuleHtml > negated Collection rule (NOT button active)', op: 'miRule', inputs: ['!Collection:Star Wars'] },
    { title: 'getMediaInfoRuleHtml > numeric Year rule with op', op: 'miRule', inputs: ['Year:>=:1990'] },
    { title: 'getMediaInfoRuleHtml > IsPlayed current-user rule', op: 'miRule', inputs: ['IsPlayed:__current__:=:Watched'] },
    { title: 'getMediaInfoRuleHtml > MediaType Episode rule (include-parent checkbox visible)', op: 'miRule', inputs: ['MediaType:Episode'] },
    { title: 'getMediaInfoRuleHtml > MediaType EpisodeIncludeSeries rule (checkbox checked)', op: 'miRule', inputs: ['MediaType:EpisodeIncludeSeries'] },
    { title: 'getMediaInfoRuleHtml > empty criterion renders the default Resolution row', op: 'miRule', inputs: [''] },
    // ---- getMediaInfoFilterGroupHtml ----
    {
        title: 'getMediaInfoFilterGroupHtml > first group, AND rules',
        op: 'miGroup',
        inputs: [{ Operator: 'AND', GroupOperator: 'AND', Criteria: ['MediaType:Movie', '4K'] }, 0, true],
    },
    {
        title: 'getMediaInfoFilterGroupHtml > non-first group with OR connector',
        op: 'miGroup',
        inputs: [{ Operator: 'OR', GroupOperator: 'OR', Criteria: ['720p', 'SD'] }, 1, false],
    },
    {
        title: 'getMediaInfoFilterGroupHtml > group with a negated rule',
        op: 'miGroup',
        inputs: [{ Operator: 'AND', GroupOperator: 'AND', Criteria: ['!Genre:Horror'] }, 0, true],
    },
    {
        title: 'getMediaInfoFilterGroupHtml > group with no criteria',
        op: 'miGroup',
        inputs: [{ Operator: 'AND', GroupOperator: 'AND', Criteria: [] }, 0, true],
    },
    {
        title: 'getMediaInfoFilterGroupHtml > null filter defaults to AND / AND / empty',
        op: 'miGroup',
        inputs: [null, 0, true],
    },
    // ---- readMiFiltersFromContainer ----
    {
        title: 'readMiFiltersFromContainer > simple dropdown rule round-trips via the shorthand map',
        op: 'readMi',
        inputs: [[{ op: 'AND', groupOp: 'AND', rules: [{ prop: 'Resolution', kind: 'select', val: '4K' }] }]],
    },
    {
        title: 'readMiFiltersFromContainer > numeric rule with op and number value',
        op: 'readMi',
        inputs: [[{ op: 'AND', groupOp: 'AND', rules: [{ prop: 'Year', kind: 'number', op: '<=', val: '1999' }] }]],
    },
    {
        title: 'readMiFiltersFromContainer > MediaType Episode + checked include-parent checkbox becomes EpisodeIncludeSeries',
        op: 'readMi',
        inputs: [[{ op: 'AND', groupOp: 'AND', rules: [{ prop: 'MediaType', kind: 'mediaType', val: 'Episode', includeParent: true }] }]],
    },
    {
        title: 'readMiFiltersFromContainer > MediaType Episode with unchecked checkbox stays Episode',
        op: 'readMi',
        inputs: [[{ op: 'AND', groupOp: 'AND', rules: [{ prop: 'MediaType', kind: 'mediaType', val: 'Episode', includeParent: false }] }]],
    },
    {
        title: 'readMiFiltersFromContainer > text rule with contains op (value trimmed)',
        op: 'readMi',
        inputs: [[{ op: 'AND', groupOp: 'AND', rules: [{ prop: 'Title', kind: 'text', val: '  Batman  ', textOp: 'contains' }] }]],
    },
    {
        title: 'readMiFiltersFromContainer > negated rule via data-not="1" toggle',
        op: 'readMi',
        inputs: [[{ op: 'AND', groupOp: 'AND', rules: [{ prop: 'Resolution', kind: 'select', val: '4K', not: true }] }]],
    },
    {
        title: 'readMiFiltersFromContainer > user-scoped IsPlayed rule',
        op: 'readMi',
        inputs: [[{ op: 'AND', groupOp: 'AND', rules: [{ prop: 'IsPlayed', kind: 'select', val: 'Watched', userId: '__current__' }] }]],
    },
    {
        title: 'readMiFiltersFromContainer > first group GroupOperator is forced to AND; second group keeps OR',
        op: 'readMi',
        inputs: [[
            { op: 'AND', groupOp: 'OR', rules: [{ prop: 'Resolution', kind: 'select', val: '4K' }] },
            { op: 'OR', groupOp: 'OR', rules: [{ prop: 'Resolution', kind: 'select', val: '720p' }] },
        ]],
    },
    {
        title: 'readMiFiltersFromContainer > groups with no surviving criteria are dropped',
        op: 'readMi',
        inputs: [[
            { op: 'AND', groupOp: 'AND', rules: [] },
            { op: 'AND', groupOp: 'AND', rules: [{ prop: 'Resolution', kind: 'select', val: '4K' }] },
            { op: 'AND', groupOp: 'AND', rules: [] },
        ]],
    },
    {
        title: 'readMiFiltersFromContainer > rule with empty prop produces no criterion and is dropped',
        op: 'readMi',
        inputs: [[{ op: 'AND', groupOp: 'AND', rules: [{ prop: '', kind: 'select', val: '4K' }] }]],
    },
];

function apply(op: MiOp, input: unknown): unknown {
    switch (op) {
        case 'miValue': {
            const [prop, savedOp, savedVal, savedUserId] = input as [string, string, string, string];
            return getMiValueHtml(prop, savedOp, savedVal, savedUserId, EMPTY_DEPS);
        }
        case 'miRule':
            return getMediaInfoRuleHtml((input as [string | null])[0], EMPTY_DEPS);
        case 'miGroup': {
            const [filter, idx, isFirst] = input as [MediaInfoFilterGroup | null, unknown, boolean];
            return getMediaInfoFilterGroupHtml(filter, idx, isFirst, EMPTY_DEPS);
        }
        case 'readMi':
            return readMiFiltersFromContainer(makeContainer((input as [DomGroup[]])[0]));
    }
}

describe('media-info builders (mirror of legacy snapshots)', () => {
    for (const c of CASES) {
        it(`${c.title} matches legacy snapshot`, () => {
            const expected = normalize(snapValue(PREFIX + c.title, 0));
            const actual = apply(c.op, c.inputs);
            expect(actual).toEqual(expected);
        });
    }
});

// ---------- self-check: the mirror covers every snapshot ----------

const MIRRORED_PATHS: ReadonlySet<string> = new Set(CASES.map((c) => PREFIX + c.title));

describe('mirror coverage', () => {
    it('every legacy snapshot key has a mirror case', () => {
        const missing: string[] = [];
        for (const key of Object.keys(legacySnap)) {
            const m = key.match(/^(.*) (\d+)$/);
            if (!m) continue;
            const path = m[1]!;
            const idx = Number(m[2]);
            if (!MIRRORED_PATHS.has(path)) {
                missing.push(path);
                continue;
            }
            if (idx > 1) {
                missing.push(`${path} #${idx} (only 1 mirrored)`);
            }
        }
        expect(missing).toEqual([]);
    });

    it('every mirror case has a matching legacy snapshot key', () => {
        const indexed = new Map<string, Set<number>>();
        for (const key of Object.keys(legacySnap)) {
            const m = key.match(/^(.*) (\d+)$/);
            if (!m) continue;
            const path = m[1]!;
            const idx = Number(m[2]);
            if (!indexed.has(path)) indexed.set(path, new Set());
            indexed.get(path)!.add(idx);
        }
        const orphans: string[] = [];
        for (const path of MIRRORED_PATHS) {
            const have = indexed.get(path);
            if (!have) {
                orphans.push(`${path} (no legacy snapshot at all)`);
                continue;
            }
            if (!have.has(1)) orphans.push(`${path} #1`);
        }
        expect(orphans).toEqual([]);
    });
});

// ─── Populated-deps branches (the legacy fixture caches are empty) ────────────

describe('getMiValueHtml with populated deps', () => {
    const deps: MiFilterDeps = {
        users: [{ Id: 'u1', Name: 'Alice' }, { Id: 'u2', Name: 'Bob' }],
        collections: [{ Name: 'Star Wars' }, { Name: 'He said "hi"' }],
        playlists: [{ Name: 'My Mix' }],
        tags: ['4K', 'HDR'],
    };

    it('renders resolved users in the user select with the saved user selected', () => {
        const html = getMiValueHtml('IsPlayed', '', 'Watched', 'u2', deps);
        expect(html).toContain('<option value="u1">Alice</option>');
        expect(html).toContain('<option value="u2" selected>Bob</option>');
        // The __current__ special is IsPlayed-only and stays unselected.
        expect(html).toContain('<option value="__current__">Current user (viewer)</option>');
        expect(html).toContain('<option value="__any__">Any user</option>');
    });

    it('renders collections and escapes double quotes in option values', () => {
        const html = getMiValueHtml('Collection', '', 'Star Wars', '', deps);
        expect(html).toContain('<option value="Star Wars" selected>Star Wars</option>');
        expect(html).toContain('<option value="He said &quot;hi&quot;">He said "hi"</option>');
        expect(html).toContain('<option value="">-- Select --</option>');
    });

    it('renders the tag dropdown branch when tags are cached', () => {
        const html = getMiValueHtml('Tag', 'contains', 'HDR', '', deps);
        expect(html).toContain('-- Select tag --');
        expect(html).toContain('<option value="HDR" selected>HDR</option>');
        expect(html).toContain('<option value="4K">4K</option>');
        // The dropdown branch replaces the free-text textarea entirely.
        expect(html).not.toContain('txtMiValue');
    });

    it('renders playlists from the playlist list, not the collection list', () => {
        const html = getMiValueHtml('Playlist', '', 'My Mix', '', deps);
        expect(html).toContain('<option value="My Mix" selected>My Mix</option>');
        expect(html).not.toContain('Star Wars');
    });
});

// ─── Build → read round-trip ───────────────────────────────────────────────────

describe('build → read round-trip', () => {
    it('readMiFiltersFromContainer inverts getMediaInfoFilterGroupHtml', () => {
        const html = getMediaInfoFilterGroupHtml(
            { Operator: 'AND', GroupOperator: 'AND', Criteria: ['MediaType:Movie', '4K'] },
            0,
            true,
            EMPTY_DEPS,
        );
        const container = document.createElement('div');
        container.innerHTML = html;
        expect(readMiFiltersFromContainer(container)).toEqual([
            { Operator: 'AND', GroupOperator: 'AND', Criteria: ['MediaType:Movie', '4K'] },
        ]);
    });

    it('round-trips a negated rule and the Episode checkbox', () => {
        const html = getMediaInfoFilterGroupHtml(
            { Operator: 'OR', GroupOperator: 'AND', Criteria: ['!MediaType:EpisodeIncludeSeries', 'Year:<=:1999'] },
            1,
            false,
            EMPTY_DEPS,
        );
        const container = document.createElement('div');
        container.innerHTML = html;
        expect(readMiFiltersFromContainer(container)).toEqual([
            {
                Operator: 'OR',
                GroupOperator: 'AND',
                Criteria: ['!MediaType:EpisodeIncludeSeries', 'Year:<=:1999'],
            },
        ]);
    });
});
